baseURL = 'https://onlypwned.com'
languageCode = 'en-us'
title = 'OnlyPwned'
pygmentsStyle = "monokai"
theme = "gokarna"

[params]
  avatarAltText = "avatar"
  avatarSize = "size-l"
  avatarURL = "/images/vqw.jpg"

  description = "Cybersecurity | Linux | Tech | AD "

    customHeadHTML = """
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="theme-color" content="#0b0b0b">
    <link rel="preload" as="image" href="/images/OnlyPWNEDMaain.webp">

    <style>
      html.preloader-active .wrapper {
        visibility: hidden;
      }

      #preloader {
        position: fixed;
        inset: 0;
        display: grid;
        place-items: center;
        background: #0b0b0b;
        z-index: 9999;
        opacity: 1;
        transition: opacity .6s ease;
      }
      
      #preloader.preloader-hide {
        opacity: 0;
        pointer-events: none;
      }

      #preloader img {
        max-width: 60vw;
        max-height: 30vh;
        animation: zoomIn 3s ease-out forwards;
        will-change: transform, opacity;
      }
      
      @keyframes zoomIn {
        from { transform: scale(.2); opacity: .6; }
        to   { transform: scale(1); opacity: 1; }
      }

      /* Responsive adjustments */
      @media (max-width: 768px) {
        #preloader img {
          max-width: 100vw;
          max-height: 50vh;
        }
      }

      /* Accessibility: Disable animation if user prefers reduced motion */
      @media (prefers-reduced-motion: reduce) {
        #preloader img { animation: none; }
      }
    </style>

    <script>
      // This script runs instantly. If it's the homepage, it adds the class to hide the main content.
      (function () {
        if (location.pathname === "/") {
          document.documentElement.classList.add("preloader-active");
        }
      })();
    </script>
  """

  customFooterHTML = """
    <script>
      (function () {
        var pre = document.getElementById("preloader");
        if (!pre) return; 
        var DURATION_MS = 2000; 

        function finish() {
          document.documentElement.classList.remove("preloader-active");
          pre.classList.add("preloader-hide");
          pre.addEventListener("transitionend", function () { pre.remove(); }, { once: true });
        }

        window.addEventListener('load', function() {
            setTimeout(finish, DURATION_MS);
        });

      })();
    </script>
  """


  footer = "Sameep Shukla"

  socialIcons = [
    {name = "twitter", url = "https://x.com/xov3d"},
    {name = "email", url = "mailto:shuklasameep16@gmail.com"}
  ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "resume"
    url = "/resume/"
    weight = 2

  [[menu.main]]
    name = "notes"
    url = "/notes/"
    weight = 3

  [[menu.main]]
    name = "creatives"
    url = "/creatives/"
    weight = 4

  [[menu.main]]
    name = "blogs"
    url = "/blogs/"
    weight = 5

  [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 6

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/sameepshukla"
    weight = 7
    pre = "<span data-feather='github'></span>"
    post = ""

enableRobotsTXT = true

metaKeywords = ["blog", "Cybersecurity", "Security Engineer", "Cyber Security", "Active Directory"]

tags = ["blog", "Cybersecurity", "Active Directory", "Windows", "Linux", "personal", "PowerShell"]
