baseURL = 'https://onlypwned.com'
languageCode = 'en-us'
title = 'OnlyPwned'
pygmentsStyle = "monokai"
theme = "gokarna"

[params]
  avatarAltText = "avatar"
  avatarSize = "size-l"
  avatarURL = "/images/vqw.jpg"

  description = "Cybersecurity | Linux | Tech | AD "

  customHeadHTML = """
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#0b0b0b">

    <link rel="preload" as="image" href="/images/OnlyPWNEDMaain.webp">

    <style>
      html.preloader-active body { visibility: hidden; }

      #preloader {
        position: fixed;
        inset: 0;
        display: grid;
        place-items: center;
        background: #0b0b0b;
        z-index: 9999;
        opacity: 1;
        transition: opacity .6s ease;
      }

      #preloader img {
        max-width: 60vw;
        max-height: 30vh;
        width: auto;
        height: auto;
        animation: zoomIn 3s ease-out forwards; 
        will-change: transform, opacity;
      }

      @media (max-width: 768px) {
      #preloader img {
      max-width: 100vw;  
      max-height: 50vh; 
      }
      }

      @keyframes zoomIn {
        from { transform: scale(.2); opacity: .6; }
        to   { transform: scale(1);  opacity: 1; }
      }

      #preloader.preloader-hide { opacity: 0; pointer-events: none; }

      @media (prefers-reduced-motion: reduce) {
        #preloader img { animation: none; }
      }
    </style>

    <script>
      (function () {
        if (location.pathname !== "/") return;

        document.documentElement.classList.add("preloader-active");

        var markup =
          '<div id="preloader" aria-hidden="true" role="img">'
          + '<img src="/images/OnlyPWNEDMaain.webp" alt="OnlyPwned logo"'
          + ' loading="eager" decoding="sync" fetchpriority="high" />'
          + '</div>';
        document.write(markup);
      })();
    </script>

    <noscript>
      <style>
        #preloader { display: none !important; }
        html.preloader-active body { visibility: visible !important; }
      </style>
    </noscript>
  """




    customFooterHTML = """
    <script>
      (function () {
        var pre = document.getElementById("preloader");
        if (!pre) return; 

        var DURATION_MS = 300; 

        function finish() {
          document.documentElement.classList.remove("preloader-active");
          pre.classList.add("preloader-hide");
          pre.addEventListener("transitionend", function () { pre.remove(); }, { once: true });
        }

        setTimeout(finish, DURATION_MS);

        setTimeout(function () {
          if (document.documentElement.classList.contains("preloader-active")) finish();
        }, DURATION_MS + 200);
      })();
    </script>
  """


  footer = "Sameep Shukla"

  socialIcons = [
    {name = "twitter", url = "https://x.com/xov3d"},
    {name = "email", url = "mailto:shuklasameep16@gmail.com"}
  ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "resume"
    url = "/resume/"
    weight = 2

  [[menu.main]]
    name = "notes"
    url = "/notes/"
    weight = 3

  [[menu.main]]
    name = "creatives"
    url = "/creatives/"
    weight = 4

  [[menu.main]]
    name = "blogs"
    url = "/blogs/"
    weight = 5

  [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 6

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/sameepshukla"
    weight = 7
    pre = "<span data-feather='github'></span>"
    post = ""

enableRobotsTXT = true

metaKeywords = ["blog", "Cybersecurity", "Security Engineer", "Cyber Security", "Active Directory"]

tags = ["blog", "Cybersecurity", "Active Directory", "Windows", "Linux", "personal", "PowerShell"]
